"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Header from "../../components/layout/Header";
import Icon from "../../components/ui/Icon";
import { authenticatedFetch } from "../../features/auth/auth-client";

type Client = { id: string; nombreRazonSocial: string };
type DocumentRecord = { id: string; nombreArchivo: string; mimeType: string; tamanoBytes: string | number; estado: string; cargadoEn?: string | null; cliente?: Client | null; tipoDocumento?: { nombre: string } | null; periodo?: { anio: number; mes: number } | null };
const states = ["RECIBIDO", "PENDIENTE_REVISION", "REVISADO", "ARCHIVADO"];
const inputClass = "h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-[#252f46] focus:border-[#735044] focus:outline-none focus:ring-2 focus:ring-[#ead8d0]";

export default function Page() {
  const [documents, setDocuments] = useState<DocumentRecord[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [types, setTypes] = useState<string[]>([]);
  const [search, setSearch] = useState(""); const [clientId, setClientId] = useState(""); const [period, setPeriod] = useState(""); const [type, setType] = useState(""); const [state, setState] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [uploadClientId, setUploadClientId] = useState(""); const [uploadPeriod, setUploadPeriod] = useState(""); const [uploadType, setUploadType] = useState(""); const [uploadState, setUploadState] = useState("RECIBIDO"); const [observation, setObservation] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const query = useMemo(() => new URLSearchParams(Object.entries({ buscar: search, clienteId: clientId, periodo: period, tipo: type, estado: state }).filter(([, value]) => value)).toString(), [search, clientId, period, type, state]);

  async function loadData() {
    setLoading(true); setError("");
    try {
      const [documentsResponse, clientsResponse, typesResponse] = await Promise.all([authenticatedFetch(`/documentos${query ? `?${query}` : ""}`), authenticatedFetch("/clientes"), authenticatedFetch("/documentos/tipos-sugeridos")]);
      if (!documentsResponse.ok || !clientsResponse.ok || !typesResponse.ok) throw new Error("No se pudo cargar el archivo documental.");
      setDocuments(await documentsResponse.json() as DocumentRecord[]);
      const loadedClients = await clientsResponse.json() as Client[];
      setClients(loadedClients); setTypes(await typesResponse.json() as string[]);
      setUploadClientId((current) => current || loadedClients[0]?.id || "");
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "No se pudo cargar el archivo documental."); } finally { setLoading(false); }
  }
  useEffect(() => { void loadData(); }, [query]);

  async function uploadDocument(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!selectedFile || !uploadClientId || !uploadPeriod || !uploadType) { setError("Selecciona un archivo, cliente, período y tipo de documento."); return; }
    setSaving(true); setError(""); setMessage("");
    const formData = new FormData(); formData.append("archivo", selectedFile); formData.append("clienteId", uploadClientId); formData.append("periodo", uploadPeriod); formData.append("tipo", uploadType); formData.append("estado", uploadState); formData.append("observacion", observation);
    try {
      const response = await authenticatedFetch("/documentos", { method: "POST", body: formData });
      if (!response.ok) { const data = await response.json().catch(() => null) as { message?: string } | null; throw new Error(data?.message || "No se pudo cargar el documento."); }
      setMessage("Documento cargado correctamente."); setSelectedFile(null); setUploadPeriod(""); setObservation(""); setIsModalOpen(false); await loadData();
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "No se pudo cargar el documento."); } finally { setSaving(false); }
  }
  async function downloadDocument(document: DocumentRecord) {
    setError("");
    try { const response = await authenticatedFetch(`/documentos/${document.id}/descargar`); if (!response.ok) throw new Error("No se pudo descargar el documento."); const url = URL.createObjectURL(await response.blob()); const link = window.document.createElement("a"); link.href = url; link.download = document.nombreArchivo; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "No se pudo descargar el documento."); }
  }
  const pendingCount = documents.filter((document) => document.estado === "PENDIENTE_REVISION").length;
  return <main className="relative space-y-6">
    <Link href="/admin" className="inline-flex items-center gap-2 rounded text-sm font-medium text-[#735044] underline-offset-4 hover:underline"><Icon name="home" /> Volver al panel principal</Link>
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-6"><div className="flex items-start gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#efe0da] text-[#735044]"><Icon name="file" className="h-6 w-6" /></span><Header title="Documentos" description="Carga, consulta y descarga documentos asociados a cada cliente y período." /></div><button type="button" onClick={() => setIsModalOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-[#252f46] px-4 py-3 text-sm font-semibold text-white hover:bg-[#344463]"><Icon name="plus" /> Subir documento</button></div>
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}{message && <p role="status" className="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{message}</p>}
    <p className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><strong>Visibilidad de clientes pendiente.</strong> Los documentos se guardan sin exponerlos en el portal del cliente.</p>
    <dl className="grid gap-4 sm:grid-cols-3"><Metric label="Documentos registrados" value={loading ? "…" : documents.length} /><Metric label="Pendientes de revisión" value={loading ? "…" : pendingCount} /><Metric label="Disponibles en portal" value="Pendiente" /></dl>
    <section className="rounded-xl border border-slate-200 bg-white p-5" aria-labelledby="filters-title"><h2 id="filters-title" className="font-semibold text-[#252f46]">Buscar y filtrar</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar archivo o cliente" className={inputClass} /><select value={clientId} onChange={(event) => setClientId(event.target.value)} className={inputClass}><option value="">Cliente: todos</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.nombreRazonSocial}</option>)}</select><input type="month" value={period} onChange={(event) => setPeriod(event.target.value)} className={inputClass} aria-label="Filtrar por período" /><select value={type} onChange={(event) => setType(event.target.value)} className={inputClass}><option value="">Tipo: todos</option>{types.map((item) => <option key={item}>{item}</option>)}</select><select value={state} onChange={(event) => setState(event.target.value)} className={inputClass}><option value="">Estado: todos</option>{states.map((item) => <option key={item}>{formatState(item)}</option>)}</select></div></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white" aria-labelledby="documents-title"><div className="border-b border-slate-200 p-5"><h2 id="documents-title" className="font-semibold text-[#252f46]">Archivo documental</h2><p className="mt-1 text-sm text-slate-600">{loading ? "Cargando documentos…" : `${documents.length} documento(s) encontrado(s)`}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#252f46] text-white"><tr>{["Archivo", "Cliente", "Categoría", "Período", "Fecha", "Estado", "Acciones"].map((heading) => <th key={heading} className="px-5 py-4 font-medium">{heading}</th>)}</tr></thead><tbody>{documents.map((document) => <tr key={document.id} className="border-t border-slate-200"><td className="max-w-56 truncate px-5 py-4 font-medium text-[#252f46]" title={document.nombreArchivo}>{document.nombreArchivo}<span className="mt-1 block text-xs font-normal text-slate-500">{formatBytes(document.tamanoBytes)}</span></td><td className="px-5 py-4">{document.cliente?.nombreRazonSocial || "Cliente no disponible"}</td><td className="px-5 py-4">{document.tipoDocumento?.nombre || "Sin categoría"}</td><td className="px-5 py-4">{formatPeriod(document.periodo)}</td><td className="px-5 py-4">{document.cargadoEn ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium" }).format(new Date(document.cargadoEn)) : "-"}</td><td className="px-5 py-4"><Status status={document.estado} /></td><td className="px-5 py-4"><button type="button" onClick={() => void downloadDocument(document)} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-[#252f46] hover:bg-slate-50"><Icon name="download" className="h-4 w-4" /> Descargar</button></td></tr>)}</tbody></table>{!loading && documents.length === 0 && <p className="p-8 text-center text-sm text-slate-600">No hay documentos que coincidan con los filtros.</p>}</div></section>
    {isModalOpen && <div role="dialog" aria-modal="true" aria-labelledby="upload-title" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onClick={() => !saving && setIsModalOpen(false)}><form onSubmit={uploadDocument} onClick={(event) => event.stopPropagation()} className="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><h2 id="upload-title" className="text-lg font-semibold text-[#252f46]">Subir documento</h2><p className="mt-1 text-sm text-slate-600">Máximo 10 MB. El documento quedará asociado al cliente y período seleccionados.</p></div><button type="button" onClick={() => setIsModalOpen(false)} className="text-slate-500">Cerrar</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-[#252f46] sm:col-span-2">Archivo<input type="file" required onChange={(event) => setSelectedFile(event.target.files?.[0] || null)} className="mt-1 block w-full text-sm" /></label><label className="text-sm font-medium text-[#252f46]">Cliente<select required value={uploadClientId} onChange={(event) => setUploadClientId(event.target.value)} className={`mt-1 ${inputClass}`}><option value="">Selecciona un cliente</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.nombreRazonSocial}</option>)}</select></label><label className="text-sm font-medium text-[#252f46]">Período<input required type="month" value={uploadPeriod} onChange={(event) => setUploadPeriod(event.target.value)} className={`mt-1 ${inputClass}`} /></label><label className="text-sm font-medium text-[#252f46]">Categoría<select required value={uploadType} onChange={(event) => setUploadType(event.target.value)} className={`mt-1 ${inputClass}`}><option value="">Selecciona una categoría</option>{types.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-medium text-[#252f46]">Estado<select value={uploadState} onChange={(event) => setUploadState(event.target.value)} className={`mt-1 ${inputClass}`}>{states.map((item) => <option key={item} value={item}>{formatState(item)}</option>)}</select></label><label className="text-sm font-medium text-[#252f46] sm:col-span-2">Observación<textarea value={observation} onChange={(event) => setObservation(event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-slate-300 p-3 text-sm" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={saving} onClick={() => setIsModalOpen(false)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-[#252f46]">Cancelar</button><button type="submit" disabled={saving} className="rounded-lg bg-[#252f46] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Cargando…" : "Cargar documento"}</button></div></form></div>}
  </main>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><dt className="text-sm text-slate-600">{label}</dt><dd className="mt-3 text-2xl font-semibold text-[#252f46]">{value}</dd></div>; }
function Status({ status }: { status: string }) { const tone = status === "REVISADO" ? "border-green-200 bg-green-50 text-green-800" : status === "PENDIENTE_REVISION" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-slate-200 bg-slate-50 text-slate-700"; return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${tone}`}>{formatState(status)}</span>; }
function formatState(value: string) { return value.replaceAll("_", " ").toLocaleLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toLocaleUpperCase()); }
function formatPeriod(period?: { anio: number; mes: number } | null) { return period ? `${String(period.mes).padStart(2, "0")}/${period.anio}` : "-"; }
function formatBytes(value: string | number) { const bytes = Number(value); return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
